version: '3.3'
services:

  frontend:
    build: ../frontend
    ports:
      - "3001:3001"

  cypress:
    image: "cypress/included:13.8.1"
    environment:
      - CYPRESS_baseUrl=http://frontend:3001
    working_dir: /e2e
    volumes:
      - ./:/e2e 
    depends_on:
      - frontend

  # # Service for the PostgreSQL database
  # db:
  #   image: postgres:13
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   depends_on:
  #     - cypress

  # # Service for the Ruby on Rails web application
  # backend:
  #   build: ../backend
  #   working_dir: /app/backend
  #   command: bundle exec rails s -p 3000 -b '0.0.0.0'
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db
  #   environment:
  #     DATABASE_URL: postgres://postgres:postgres@db:5432/backend
    
      
# Define a volume for storing PostgreSQL data
# volumes:
#   postgres_data: